---
name: 'web3-publish'
description: 'The easiest way to manage web3 content.'
branding:
  icon: 'upload-cloud'
  color: 'green'
inputs:
  secret:
    description: 'Secret key for name publishing.'
    required: true
  glob:
    description: 'Matches to the glob pattern will be individually published.'
    required: true
  name:
    description: "What is the human-readable name for your content? Currently \"
      'path' will use the file (or directory, depending on 'as' value)."
    required: false
  as:
    description: "What data type are you uploading? 'dag', 'dir', 'wrap', or \"
      'file', default: 'dag'. Are you publishing files ('file'), a data \"
      structure ('dag'), or a directory ('dir')? If you're publishing a \"
      directory 'wrap' will publish the directory itself, whereas 'dir' will \"
      publish its contents (e.g. 'data', the directory, versus 'data/*', its \"
      contents)."
    required: false
  published:
    description: 'Whether the content is published. Default false.'
    required: false
  skip:
    description: 'Whether to skip key generation and simply use the passed secret.'
    required: false
  core:
    description: "The core (namespace) that you want to publish your names under. \"
    Default is 'kbt'."
    required: false
  domain:
    description: "The custom domain to which we're publishing (requires \"
    registration). Includes scheme (default: 'https://api.pndo.xyz')."
    required: false
outputs:
  roots:
    description: 'Content addresses created.'
runs:
  using: 'node16'
  main: 'dist/index.js'
